apiVersion: v1
kind: Service
metadata:
  name: product-service-app # this name should match in application.properties for interservice communication. couponService.url =http://coupon-service-app:8080/couponapi/coupons/
spec:
  selector:
    app: product-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30002
