apiVersion: v1
kind: Service
metadata:
  name: application-db-server
spec:
  selector:
    app: mysql
  type: NodePort
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30001
