apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "12345678"
            - name: MYSQL_DATABASE
              value: "mydb"
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: mysql-configmap-volume
      volumes:
        - name: mysql-configmap-volume
          configMap:
            name: mysql-configmap